language: ruby
rvm:
  - 2.0.0

env:
  - DB=postgresql

script: bundle exec rspec spec

# Set up database
before_script:
  - psql -c 'create database tracker_test;' -U postgres
  - DB=postgresql
  - bundle exec rake db:migrate
# You may need this for rails 3.2 applications
  - bundle exec rake db:test:prepare
