development:
  adapter: postgresql
  encoding: unicode
  database: tracker_development
  pool: 5
  timeout: 5000
  username: tracker
  password:

test:
  adapter: postgresql
  database: tracker_test
  pool: 5
  timeout: 5000
  username: tracker
  password:

production:
  adapter: postgresql
  database: tracker_production
  pool: 5
  timeout: 5000
  username: tracker
  password:



