
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

test:
  adapter: postgresql
  host: localhost
  database: tracker_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  database: tracker
  pool: 5
  timeout: 5000


