development:
  adapter: postgresql
  encoding: unicode
  database: tracker_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  host: localhost
  database: tracker_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  database: tracker
  pool: 5
  timeout: 5000


