development:
  adapter: postgresql
  encoding: unicode
  database: tracker_dev
  pool: 5
  timeout: 5000
  username: boottracker
  password:

test:
  adapter: postgresql
  host: localhost
  database: tracker_test
  pool: 5
  timeout: 5000
  username: boottracker
  password:

production:
  adapter: postgresql
  host: localhost
  database: tracker
  pool: 5
  timeout: 5000
  username: boottracker
  password:



